// Every sentence the Walk Check screens show, in English and Spanish. Ported from the static build (ui/app.js, the
// team's Walk Check UI) and held to the copy rules at the top of src/lib/i18n.ts: never "safe", never "qualifies",
// plain words. Positional arguments (`A`) are names, counts and distances already formatted by the caller.
/* eslint-disable @typescript-eslint/no-explicit-any */
import { HISD_LINE } from "./contacts";

type A = any;
const DIR_ES: Record<string, string> = { N: "norte", NE: "noreste", E: "este", SE: "sureste", S: "sur", SW: "suroeste", W: "oeste", NW: "noroeste" };

const en = {
      home_h:'What does your child’s walk to the new school cross?',home_b:'Seven HISD elementary schools closed this year. Type your address to see what the new walk crosses, where to cross, and how to ask for a bus or a school zone.',
      addr:'Your home address',addr_ph:'Street address, Houston, TX',check:'Check my walk',finding:'Finding your address…',pick:'Pick my home on a map',trya:'Or try a spot in a closed school’s area:',
      notfound:'We couldn’t find that address. Add the ZIP code, or pick your home on the map.',
      grade_q:'Your child is in',grade_k:'K to 5th',grade_pk:'Pre-K',found:'We found',fix:'Not right? Fix it',usemine:'Use my own address',mins:(n: A)=>`about ${n} min`,shuttle_s:'shuttle until 2028',
      ask_rail:'Ask: HISD for a bus stop, the City for a guard',ask_toc:(p: A)=>`Ask: the City, through the principal of ${p}`,ask_local:'Ask: the City, through 311 and your principal',key:'Key',
      copy:'Copy message',copied:'Copied',close:'Close',opens_mail:'Opens your email app with this message.',opens_msgs:'Opens your messages with this text ready to send.',showmap:'Show on map',walkto:'Walk to',
      shared_h:'Someone shared this walk with you.',shared_b:'Check your own address',
      coop_win:'Hold Ctrl and scroll to zoom the map',coop_mac:'Hold ⌘ and scroll to zoom the map, or pinch on a trackpad',coop_touch:'Use two fingers to move the map',
      days:(n: A)=>`${n} days`,page1:'1 page',doc_en:'The document is in English because the school files it.',nav_zones:'Schools that closed',nav_staff:'For City and HISD staff',
      plan_title:'Walk plan',plan_to:(n: A)=>`Walk plan to ${n}`,plan_for:'For the home at',doc_cross:(n: A)=>`${n} crossing${n===1?'':'s'}`,doc_none:'nothing to cross',plan_order:'Where to cross, in order',plan_nothing:'Nothing on the City’s lists',plan_anyway:'Walk it once anyway to see the corners.',plan_tracks:'Train tracks',
      plan_shuttle:(from: A, addr: A, m: A, x: A)=>`<b>Free HISD shuttle through 2027–28.</b> Pickup at ${from}, ${addr}, ${m} mi from home. The walk there ${x}. Stop and times: ask the school or call HISD, ${HISD_LINE}.`,plan_xnone:'crosses nothing on the City’s lists',plan_xsome:(l: A)=>`crosses ${l}`,
      plan_bring:(school: A, who: A, phone: A)=>`<b>Want a bus stop or a school zone?</b> Bring this page to the front office of ${school} and ask for ${who}${phone?' · '+phone:''}.`,plan_principal:'the principal',plan_foot:'Straight lines, not streets. Traffic lights only; guards and painted crosswalks are not on public maps.',plan_dates:(a: A, b: A)=>`City crash lists 2022 · HISD rail ${a} · signals read ${b}`,
      src_use:['Campus points and addresses','The seven closed zones','Which school an address walks to now','Roads marked “dangerous for people walking”, with crash counts','High-injury roads, with crash counts','Train tracks','“Cross at the traffic light at…”','“Cross the tracks at the public crossing on…”','Whether a street can get a school zone on paper','Where on campus a shuttle can stop'],
      other_lang:'¿Prefiere español?',other_go:'Cambiar a español',dismiss:'Cerrar',
      closed:'Schools that closed',closed_b:'Each closed school, and the school its families walk to now.',see:'See the walk',how:['Type your address','See what the walk crosses and where to cross','Give your principal the request'],
      staff_h:'For City and HISD staff',staff_b:'The same data, sorted for the people who can change the walks.',
      staff:[{h:'Closed zones data',b:'Per closed zone: how much farther the walk is, and what share now crosses a dangerous road or active rail.',href:'#/data'},{h:'Corridors',b:'Every road and track a new walk crosses, sorted so the places with no traffic light come first, with what the City can do there.',href:'#/corridors'},{h:'Before April 15',b:'The streets by receiving school, the City’s written paths for a school zone, and a filled-in draft application for each principal.',href:'#/april15'}],
      src_h:'Where the data comes from',src_b:'Public HISD, City of Houston, Houston TranStar and federal railroad data. Lines go straight from home to school, so a real walk crosses at least what you see here.',src_link:'See every source and date',
      prek_h:'Is your child in Pre-K?',prek_why:'Pre-K has different bus rules, so we ask once.',yes:'Yes',yes_s:'Pre-K 3 or Pre-K 4',no:'No',no_s:'Kindergarten to 5th grade',
      verdict:(to: A, r: A, k: A)=>{const p=[];if(r)p.push(`${r} dangerous road${r>1?'s':''}`);if(k)p.push(k>1?`${k} railroads`:'a railroad');return `Your child’s walk to ${to} crosses ${p.length?p.join(' and '):'nothing on the City’s lists'}.`;},
      lastyear:'Last year',now:'Now',nothing:'nothing to cross',crossings:(n: A)=>`${n} crossing${n===1?'':'s'}`,straight:'in a straight line',
      where:'Where to cross',inorder:'In the order your child meets them, starting from home.',
      tag_ped:'On the City’s dangerous-for-walking list',tag_hin:'High-injury road',tag_rail:'Active train tracks',
      crashes:(pc: A, pd: A)=>pc||pd?`${pc} ${pc===1?'person':'people'} hit walking here, ${pd} killed (City count, 2022).`:'No pedestrian crashes in the City’s 2022 count on this stretch.',
      adv_sig:(n: A, f: A, d: A)=>`Cross at the traffic light at ${n}, ${f} ft ${d} of where the straight line meets the road.`,
      adv_nosig:(n: A, m: A)=>`No traffic light within 800 ft of where the line crosses.${n?` The nearest is ${n}, ${m} mi away.`:''} Cross at a corner, never mid-block.`,
      adv_x:(n: A, f: A, d: A, g: A)=>`Cross the tracks only at the public crossing on ${n}, ${f} ft ${d}${g}.`,gates:', which has gates',flash:', which has flashing lights',
      adv_nox:(n: A, m: A)=>`No public rail crossing within 800 ft.${n?` The nearest is on ${n}, ${m} mi away.`:''} Never cross the tracks anywhere else.`,
      who:'Who can change it',
      who_rail:'HISD can put a bus stop on the home side of the tracks. The City can add a sidewalk to the public crossing and a guard at it.',
      who_toc:(p: A)=>`The City. A school zone here: the principal of ${p} applies by April 15. A crossing guard: the City decides, on the school’s recommendation. A crosswalk or signal study: report through 311.`,
      who_local:'The City. A school zone is not an option here under the City’s rules (a local street that does not border the school). Ask the principal to request a crossing guard, and report a crosswalk or signal study through 311.',
      shuttle_h:(y: A)=>`Free HISD shuttle from ${y}, through the 2027–28 school year`,
      shuttle_b:(from: A, a: A, m: A, x: A)=>`The bus picks up at ${from}, ${a}, about ${m} mi from home. The walk there ${x}.`,
      xnone:'crosses nothing on the City’s lists',xsome:(list: A)=>`crosses ${list}`,
      shuttle_c:`HISD has not published where on campus it stops or when. Ask the school, or call HISD’s closure family line, ${HISD_LINE}.`,
      after_h:'After the shuttle ends',after_b:(to: A, m: A)=>`From fall 2028, HISD buses only students who live 2 miles or more from school. This home is about ${m} mi from ${to}, so it will not get a bus for distance. The other way is a hazardous-route request, and this page gathers the evidence for it.`,
      after_prek:'Pre-K is not covered by the bus or the shuttle unless your child has an IEP or 504 plan. Ask the principal. A school zone still helps.',
      note_lines:'Lines go straight from home to school. A walk on real streets crosses at least these roads and tracks, often more.',
      note_lights:'Traffic lights only. Crossing guards, stop signs and painted crosswalks are not on any public map, so a corner with a guard still shows as “no traffic light”.',
      dates:'Data dates',
      gethelp:'Get help',askzone:'Ask for a school zone',print:'Print',print_plan:'Print walk plan',share:'Share',back:'Back',
      map_walk:'This year’s walk',map_pick:'Walk to the shuttle',map_x:'Where to cross',map_light:'Light or rail crossing',map_road:'Dangerous road',map_rail:'Train tracks',map_zone:'The closed school’s old zone',
      help_h:'Two requests your principal can send',help_b:'You don’t fill anything out. Open one, check it, then print it or share it with the school.',
      bus_h:'Ask HISD for a bus stop',bus_s:'For a walk HISD calls hazardous. Any time of year. Only HISD decides.',zone_h:'Ask the City for a school zone',zone_s:'20 mph signs and flashing lights on a street your child crosses. Only the principal can apply.',deadline:'Applications close April 15',open_bus:'Open the bus request',open_zone:'Open the school zone request',
      give:'Give it to',principal:'Principal',principal_of:(s: A)=>`The principal of ${s}`,front:'Ask at the front office',call:'Call',school:'School',address:'Address',hisd_line:'HISD closure family line',council:'Neighborhood council',
      inside:'What’s in the request',steps_h:'How this works',
      bus_steps:['Print this or share it with the school','Your principal files it with HISD Transportation','HISD reviews the walk and can add a stop'],
      zone_steps:['Print this or share it with the school','Your principal sends it to Public Works by April 15','The City studies the street and Council votes in July'],
      bus_items:['The streets and the City’s crash counts','The railroad crossing, if any','A suggested bus stop near your home','Room to add neighbors on your street'],
      again:'Ask again every fall until 2028.',dl_h:'Deadline: April 15',dl_s:'Signs go up for the next school year.',streets:'Streets to include',streets_none:'No street on this walk is on one of the City’s written paths to a school zone. The request asks for a crossing guard and a crosswalk instead.',
      preview:'This is the page your principal gets',self_file:'Or file it yourself on HISD’s online form',print_req:'Print the request',
      share_h:'Share this walk',share_school:'Share with the school',your_msg:'Your message',
      zones_h:'What the closures changed',big:'8 in 10',big_t:'of the area in the seven closed zones now has a walk that crosses a dangerous road or train tracks.',big_s:'Before the closures: 5 in 10.',shareof:'Share of each zone’s area whose walk crosses a dangerous road or train tracks',lb:'Walk before',ln:'Walk now',tap:'Tap a school to see its walk.',checkaddr:'Check my address',pct_note:'Percentages are shares of each zone’s area, sampled on an even grid. They are not counts of students or homes.',
      in10:'in 10',all:'Nearly all',zd_t:'of homes now cross a dangerous road or train tracks on the way to school.',zd_b:(b: A)=>`Before the closures: ${b} in 10.`,haz:'Crosses a dangerous road or tracks',railx:'Crosses train tracks',farther:'farther, for a typical home',over2:'live 2+ miles away, the distance that earns a bus',longest:'longest walk in the zone',
      pickup_h:'The walk to the shuttle pickup',pickup_b:(n: A, a: A)=>`The bus picks up at ${n}, ${a}, the same walk as last year. Roads crossed most on that walk:`,
      nz_h:'This address is not in one of the seven closed zones.',nz_b:'Your child’s school did not change this year, so there is no new walk to check.',seeclosed:'See the schools that closed',another:'Try another address',know:'Know a family near Burrus, Port Houston, Alcott, Briscoe, Franklin, Henderson or Ross?',
      pick_h:'Tap your home on the map',pick_b:'The seven closed zones are outlined. Tap inside one.',use:'Use this spot',spot:'Spot on the map',
      plan_h:'Walk plan',bring:'Want a bus stop or a school zone?',bring_b:(n: A, p: A)=>`Bring this page to the front office and ask for ${n}${p?' · '+p:''}.`,
      staff_only:'Staff pages are in English.',sources_h:'Where the data comes from',sources_b:'Each layer below is public. The dates are when the owner last edited it, or when we read it.',
      src_cols:['Source','What it gives this site','Date']
    }
;

export type UiDict = typeof en;

const es: UiDict = {
      home_h:'¿Qué cruza su hijo en el camino a la nueva escuela?',home_b:'Siete primarias de HISD cerraron este año. Escriba su dirección para ver qué cruza el nuevo camino, dónde cruzar y cómo pedir un autobús o una zona escolar.',
      addr:'Su dirección',addr_ph:'Dirección, Houston, TX',check:'Revisar el camino',finding:'Buscando su dirección…',pick:'Marcar mi casa en el mapa',trya:'O pruebe un punto en la zona de una escuela cerrada:',
      notfound:'No encontramos esa dirección. Agregue el código postal, o marque su casa en el mapa.',
      grade_q:'Su hijo está en',grade_k:'Kínder a 5.º',grade_pk:'Pre-K',found:'Encontramos',fix:'¿No es correcta? Corríjala',usemine:'Usar mi dirección',mins:(n: A)=>`unos ${n} min`,shuttle_s:'autobús hasta 2028',
      ask_rail:'Pida: a HISD una parada, a la Ciudad un guardia',ask_toc:(p: A)=>`Pida: a la Ciudad, por medio del director de ${p}`,ask_local:'Pida: a la Ciudad, por el 311 y su director',key:'Leyenda',
      copy:'Copiar mensaje',copied:'Copiado',close:'Cerrar',opens_mail:'Abre su correo con este mensaje.',opens_msgs:'Abre sus mensajes con este texto listo para enviar.',showmap:'Ver en el mapa',walkto:'Camino a',
      shared_h:'Alguien compartió este camino con usted.',shared_b:'Revise su propia dirección',
      coop_win:'Mantenga Ctrl y desplace para acercar el mapa',coop_mac:'Mantenga ⌘ y desplace para acercar el mapa, o pellizque en el trackpad',coop_touch:'Use dos dedos para mover el mapa',
      days:(n: A)=>`${n} días`,page1:'1 página',doc_en:'El documento va en inglés porque lo presenta la escuela.',nav_zones:'Escuelas que cerraron',nav_staff:'Para personal de la Ciudad y de HISD',
      plan_title:'Plan del camino',plan_to:(n: A)=>`Plan del camino a ${n}`,plan_for:'Para la casa en',doc_cross:(n: A)=>`${n} cruce${n===1?'':'s'}`,doc_none:'nada que cruzar',plan_order:'Dónde cruzar, en orden',plan_nothing:'Nada de las listas de la Ciudad',plan_anyway:'Camínelo una vez de todos modos para ver las esquinas.',plan_tracks:'Vías de tren',
      plan_shuttle:(from: A, addr: A, m: A, x: A)=>`<b>Autobús gratis de HISD hasta 2027–28.</b> Recoge en ${from}, ${addr}, a ${m} millas de casa. El camino hasta ahí ${x}. Parada y horarios: pregunte en la escuela o llame a HISD, ${HISD_LINE}.`,plan_xnone:'no cruza nada de las listas de la Ciudad',plan_xsome:(l: A)=>`cruza ${l}`,
      plan_bring:(school: A, who: A, phone: A)=>`<b>¿Quiere una parada de autobús o una zona escolar?</b> Lleve esta página a la oficina de ${school} y pregunte por ${who}${phone?' · '+phone:''}.`,plan_principal:'el director o la directora',plan_foot:'Líneas rectas, no calles. Solo semáforos; los guardias y los pasos pintados no están en mapas públicos.',plan_dates:(a: A, b: A)=>`Listas de choques de la Ciudad 2022 · vías HISD ${a} · semáforos leídos ${b}`,
      src_use:['Puntos y direcciones de los planteles','Las siete zonas cerradas','A qué escuela camina ahora una dirección','Calles marcadas “peligrosas para peatones”, con conteos de choques','Calles con muchos choques, con conteos','Vías de tren','“Cruce en el semáforo de…”','“Cruce las vías por el cruce público de…”','Si una calle puede tener zona escolar según las reglas','Dónde puede parar el autobús en el plantel'],
      other_lang:'Prefer English?',other_go:'Switch to English',dismiss:'Close',
      closed:'Escuelas que cerraron',closed_b:'Cada escuela cerrada, y la escuela a la que sus familias caminan ahora.',see:'Ver el camino',how:['Escriba su dirección','Vea qué cruza el camino y dónde cruzar','Entregue la solicitud a su director'],
      staff_h:'Para personal de la Ciudad y de HISD',staff_b:'Los mismos datos, ordenados para quienes pueden cambiar los caminos.',
      staff:[{h:'Datos de las zonas cerradas',b:'Por zona cerrada: cuánto más largo es el camino y qué parte ahora cruza una calle peligrosa o una vía activa.',href:'#/data'},{h:'Corredores',b:'Cada calle y vía que cruza un camino nuevo, primero los lugares sin semáforo, con lo que la Ciudad puede hacer ahí.',href:'#/corridors'},{h:'Antes del 15 de abril',b:'Las calles por escuela receptora, las reglas escritas de la Ciudad para una zona escolar y un borrador de solicitud para cada director.',href:'#/april15'}],
      src_h:'De dónde salen los datos',src_b:'Datos públicos de HISD, la Ciudad de Houston, Houston TranStar y el registro federal de ferrocarriles. Las líneas van rectas de la casa a la escuela, así que el camino real cruza al menos lo que ve aquí.',src_link:'Ver cada fuente y fecha',
      prek_h:'¿Su hijo está en Pre-K?',prek_why:'Pre-K tiene otras reglas de autobús, por eso preguntamos una vez.',yes:'Sí',yes_s:'Pre-K 3 o Pre-K 4',no:'No',no_s:'Kínder a 5.º grado',
      verdict:(to: A, r: A, k: A)=>{const p=[];if(r)p.push(`${r} calle${r>1?'s':''} peligrosa${r>1?'s':''}`);if(k)p.push(k>1?`${k} vías de tren`:'una vía de tren');return `El camino de su hijo a ${to} cruza ${p.length?p.join(' y '):'nada de las listas de la Ciudad'}.`;},
      lastyear:'El año pasado',now:'Ahora',nothing:'nada que cruzar',crossings:(n: A)=>`${n} cruce${n===1?'':'s'}`,straight:'en línea recta',
      where:'Dónde cruzar',inorder:'En el orden en que su hijo los encuentra, saliendo de casa.',
      tag_ped:'En la lista de la Ciudad de calles peligrosas para peatones',tag_hin:'Calle con muchos choques',tag_rail:'Vía de tren activa',
      crashes:(pc: A, pd: A)=>pc||pd?`${pc} persona${pc===1?'':'s'} atropellada${pc===1?'':'s'} aquí, ${pd} fallecida${pd===1?'':'s'} (conteo de la Ciudad, 2022).`:'Sin choques con peatones en el conteo 2022 de la Ciudad en este tramo.',
      adv_sig:(n: A, f: A, d: A)=>`Cruce en el semáforo de ${n}, a ${f} pies al ${DIR_ES[d]} de donde la línea recta toca la calle.`,
      adv_nosig:(n: A, m: A)=>`No hay semáforo a menos de 800 pies de donde cruza la línea.${n?` El más cercano es ${n}, a ${m} millas.`:''} Cruce en una esquina, nunca a media cuadra.`,
      adv_x:(n: A, f: A, d: A, g: A)=>`Cruce las vías solo por el cruce público de ${n}, a ${f} pies al ${DIR_ES[d]}${g}.`,gates:', que tiene barreras',flash:', que tiene luces',
      adv_nox:(n: A, m: A)=>`No hay cruce público de vías a menos de 800 pies.${n?` El más cercano está en ${n}, a ${m} millas.`:''} Nunca cruce las vías por otro lugar.`,
      who:'Quién puede cambiarlo',
      who_rail:'HISD puede poner una parada de autobús del lado de la casa. La Ciudad puede agregar una banqueta hasta el cruce público y un guardia ahí.',
      who_toc:(p: A)=>`La Ciudad. Una zona escolar aquí: el director de ${p} la solicita antes del 15 de abril. Un guardia de cruce: la Ciudad decide, con la recomendación de la escuela. Un paso peatonal o un estudio de semáforo: repórtelo al 311.`,
      who_local:'La Ciudad. Una zona escolar no aplica aquí según las reglas de la Ciudad (calle local que no colinda con la escuela). Pida al director que solicite un guardia, y reporte un paso peatonal o estudio de semáforo al 311.',
      shuttle_h:(y: A)=>`Autobús gratis de HISD desde ${y}, hasta el año escolar 2027–28`,
      shuttle_b:(from: A, a: A, m: A, x: A)=>`El autobús recoge en ${from}, ${a}, a unas ${m} millas de casa. El camino hasta ahí ${x}.`,
      xnone:'no cruza nada de las listas de la Ciudad',xsome:(list: A)=>`cruza ${list}`,
      shuttle_c:`HISD no ha publicado dónde para en el plantel ni a qué hora. Pregunte en la escuela o llame a la línea de familias de HISD, ${HISD_LINE}.`,
      after_h:'Cuando termine el autobús',after_b:(to: A, m: A)=>`Desde otoño de 2028, HISD da autobús solo a estudiantes que viven a 2 millas o más. Esta casa está a unas ${m} millas de ${to}, así que no tendrá autobús por distancia. La otra vía es una solicitud de ruta peligrosa, y esta página reúne la evidencia.`,
      after_prek:'Pre-K no está cubierto por el autobús ni el transporte, salvo con un plan IEP o 504. Pregunte al director. Una zona escolar sí ayuda.',
      note_lines:'Las líneas van rectas de la casa a la escuela. Un camino por calles reales cruza al menos estas calles y vías, a menudo más.',
      note_lights:'Solo semáforos. Los guardias, señales de alto y pasos pintados no están en ningún mapa público, así que una esquina con guardia aún aparece como “sin semáforo”.',
      dates:'Fechas de los datos',
      gethelp:'Pedir ayuda',askzone:'Pedir una zona escolar',print:'Imprimir',print_plan:'Imprimir el plan',share:'Compartir',back:'Atrás',
      map_walk:'Camino de este año',map_pick:'Camino al autobús',map_x:'Dónde cruzar',map_light:'Semáforo o cruce de vías',map_road:'Calle peligrosa',map_rail:'Vías de tren',map_zone:'Zona anterior de la escuela cerrada',
      help_h:'Dos solicitudes que su director puede enviar',help_b:'Usted no llena nada. Abra una, revísela, e imprímala o compártala con la escuela.',
      bus_h:'Pedir una parada de autobús a HISD',bus_s:'Para un camino que HISD considera peligroso. En cualquier época del año. Solo HISD decide.',zone_h:'Pedir una zona escolar a la Ciudad',zone_s:'Letreros de 20 mph y luces en una calle que cruza su hijo. Solo el director puede solicitarla.',deadline:'Cierra el 15 de abril',open_bus:'Abrir la solicitud de autobús',open_zone:'Abrir la solicitud de zona escolar',
      give:'Entregar a',principal:'Director(a)',principal_of:(s: A)=>`El director o directora de ${s}`,front:'Pregunte en la oficina',call:'Llamar',school:'Escuela',address:'Dirección',hisd_line:'Línea de familias de HISD',council:'Consejo del vecindario',
      inside:'Qué incluye la solicitud',steps_h:'Cómo funciona',
      bus_steps:['Imprima esto o compártalo con la escuela','Su director lo presenta a Transporte de HISD','HISD revisa el camino y puede agregar una parada'],
      zone_steps:['Imprima esto o compártalo con la escuela','Su director lo envía a Obras Públicas antes del 15 de abril','La Ciudad estudia la calle y el Concejo vota en julio'],
      bus_items:['Las calles y los choques registrados por la Ciudad','El cruce de la vía del tren, si lo hay','Una parada de autobús sugerida cerca de su casa','Espacio para agregar vecinos de su calle'],
      again:'Pídalo cada otoño hasta 2028.',dl_h:'Fecha límite: 15 de abril',dl_s:'Los letreros se instalan para el siguiente año escolar.',streets:'Calles a incluir',streets_none:'Ninguna calle de este camino está en una de las vías escritas de la Ciudad para una zona escolar. La solicitud pide un guardia y un paso peatonal.',
      preview:'Esta es la página que recibe su director',self_file:'O preséntelo usted en el formulario en línea de HISD',print_req:'Imprimir la solicitud',
      share_h:'Compartir este camino',share_school:'Compartir con la escuela',your_msg:'Su mensaje',
      zones_h:'Qué cambió con los cierres',big:'8 de 10',big_t:'del área de las siete zonas cerradas ahora tiene un camino que cruza una calle peligrosa o vías de tren.',big_s:'Antes de los cierres: 5 de 10.',shareof:'Parte del área de cada zona cuyo camino cruza una calle peligrosa o vías de tren',lb:'Camino antes',ln:'Camino ahora',tap:'Toque una escuela para ver su camino.',checkaddr:'Revisar mi dirección',pct_note:'Los porcentajes son partes del área de cada zona, muestreada en una cuadrícula. No son conteos de estudiantes ni de casas.',
      in10:'de 10',all:'Casi todos',zd_t:'de las casas ahora cruzan una calle peligrosa o vías de tren camino a la escuela.',zd_b:(b: A)=>`Antes de los cierres: ${b} de 10.`,haz:'Cruza una calle peligrosa o vías',railx:'Cruza vías de tren',farther:'más lejos, para una casa típica',over2:'viven a 2+ millas, la distancia que da autobús',longest:'camino más largo de la zona',
      pickup_h:'El camino a la parada del autobús',pickup_b:(n: A, a: A)=>`El autobús recoge en ${n}, ${a}, el mismo camino del año pasado. Calles que más se cruzan en ese camino:`,
      nz_h:'Esta dirección no está en una de las siete zonas cerradas.',nz_b:'La escuela de su hijo no cambió este año, así que no hay un camino nuevo que revisar.',seeclosed:'Ver las escuelas que cerraron',another:'Probar otra dirección',know:'¿Conoce a una familia cerca de Burrus, Port Houston, Alcott, Briscoe, Franklin, Henderson o Ross?',
      pick_h:'Toque su casa en el mapa',pick_b:'Las siete zonas cerradas están marcadas. Toque dentro de una.',use:'Usar este punto',spot:'Punto en el mapa',
      plan_h:'Plan del camino',bring:'¿Quiere una parada de autobús o una zona escolar?',bring_b:(n: A, p: A)=>`Lleve esta página a la oficina y pregunte por ${n}${p?' · '+p:''}.`,
      staff_only:'Las páginas para personal están en inglés.',sources_h:'De dónde salen los datos',sources_b:'Cada capa es pública. Las fechas son la última edición del dueño, o cuándo la leímos.',
      src_cols:['Fuente','Qué aporta a este sitio','Fecha']
    };

export const UI: Record<"en" | "es", UiDict> = { en, es };
