// Every word the Walk Check screens show, in English and Spanish. Short on purpose: labels, not paragraphs. Held to the
// copy rules at the top of src/lib/i18n.ts: never "safe", never "qualifies". Positional arguments (`A`) are names,
// counts and distances already formatted by the caller.
/* eslint-disable @typescript-eslint/no-explicit-any */
import { HISD_LINE } from "./contacts";

type A = any;
const DIR_ES: Record<string, string> = { N: "norte", NE: "noreste", E: "este", SE: "sureste", S: "sur", SW: "suroeste", W: "oeste", NW: "noroeste" };
const DIR_ES_SHORT: Record<string, string> = { N: "N", NE: "NE", E: "E", SE: "SE", S: "S", SW: "SO", W: "O", NW: "NO" };

const en = {
      // home
      h_check:'Check my child’s walk to school',addr:'Home address',addr_ph:'1234 Main St',go:'Safety check',checking:'Checking…',
      demo:'Use a demo address',pick:'Pick on a map',examples:'Examples',ex_sub:'Homes in the 7 closed school zones',
      bad_addr:(ex: A)=>`Add a house number and street. Example: ${ex}`,notfound:'Address not found. Try the demo or pick on a map.',
      // result
      v_red:'Danger',v_red_s:'Crossings with no traffic light',v_yellow:'Careful',v_yellow_s:'Cross only at the lights',v_green:'Clear',v_green_s:'No dangerous crossings',
      your_school:'School',dangers:'Danger points',none:'None',contacts:'Who to call',call_hisd:'Call HISD',email_city:'Email the City',school_office:'School office',
      shuttle_line:(from: A)=>`Free shuttle from ${from} until 2028`,askbus:'Ask for a bus',details:'Full details',
      d_nolight:'No light',d_nox:'No rail crossing',d_light:(f: A)=>`Light ${f}`,d_gate:(f: A)=>`Gate ${f}`,d_xing:(f: A)=>`Rail crossing ${f}`,dir:(d: A)=>d,
      rail_name:'Train tracks',mi_walk:(m: A)=>`${m} mi straight line`,
      nz_h:'Not in an HISD elementary zone',another:'Try another address',
      // nav, about
      nav_check:'Check',nav_schools:'Schools',nav_about:'About',nav_staff:'Staff',
      about_h:'About',about_b:['HISD closed 7 elementary schools in 2026.','Kids now walk farther, across busier roads.','This site shows each walk. Public data only.'],
      about_links:'Read more',
      // chat
      ask:'Ask',ask_h:'Ask about this walk',
      // walk page (full details)
      grade_q:'Grade',grade_k:'K–5',grade_pk:'Pre-K',found:'Found',fix:'Fix',usemine:'Use my address',mins:(n: A)=>`${n} min`,shuttle_s:'shuttle until 2028',
      ask_rail:'Ask HISD for a bus stop',ask_toc:(p: A)=>`Ask the City, via ${p}’s principal`,ask_local:'Ask the City via 311',key:'Key',
      copy:'Copy',copied:'Copied',close:'Close',opens_mail:'Opens email.',opens_msgs:'Opens messages.',showmap:'Map',walkto:'Walk to',
      shared_h:'Shared walk.',shared_b:'Check yours',
      coop_win:'Ctrl + scroll to zoom',coop_mac:'⌘ + scroll to zoom',coop_touch:'Two fingers to move',
      days:(n: A)=>`${n} days`,page1:'1 page',doc_en:'In English: the school files it.',
      plan_title:'Walk plan',plan_to:(n: A)=>`Walk plan to ${n}`,plan_for:'Home',doc_cross:(n: A)=>`${n} crossing${n===1?'':'s'}`,doc_none:'nothing to cross',plan_order:'Where to cross',plan_nothing:'Nothing on the City’s lists',plan_anyway:'Walk it once to see the corners.',plan_tracks:'Train tracks',
      plan_shuttle:(from: A, addr: A, m: A, x: A)=>`<b>Free HISD shuttle through 2027–28.</b> Pickup: ${from}, ${addr}, ${m} mi. The walk there ${x}. Times: HISD, ${HISD_LINE}.`,plan_xnone:'crosses nothing on the City’s lists',plan_xsome:(l: A)=>`crosses ${l}`,
      plan_bring:(school: A, who: A, phone: A)=>`<b>Bus stop or school zone?</b> Take this page to ${school}. Ask for ${who}${phone?' · '+phone:''}.`,plan_principal:'the principal',plan_foot:'Straight lines, not streets. Traffic lights only.',plan_foot_route:'Walking route on mapped streets. Traffic lights only.',plan_dates:(a: A, b: A)=>`City crash lists 2022 · HISD rail ${a} · signals ${b}`,
      src_use:['Schools','Closed zones','Zone for an address','Roads dangerous for walking','High-injury roads','Train tracks','Traffic lights','Public rail crossings','School zone rules','Shuttle stops'],
      closed:'Schools that closed',see:'See the walk',
      src_link:'Sources',
      prek_h:'Pre-K?',prek_why:'Different bus rules.',yes:'Yes',yes_s:'Pre-K 3 or 4',no:'No',no_s:'K–5',
      verdict:(to: A, r: A, k: A)=>{const p=[];if(r)p.push(`${r} dangerous road${r>1?'s':''}`);if(k)p.push(k>1?`${k} railroads`:'a railroad');return `Walk to ${to}: ${p.length?p.join(' + '):'nothing on the City’s lists'}.`;},
      lastyear:'Last year',now:'Now',nothing:'nothing to cross',crossings:(n: A)=>`${n} crossing${n===1?'':'s'}`,
      where:'Where to cross',
      tag_ped:'Dangerous for walking',tag_hin:'High-injury road',tag_rail:'Active tracks',
      crashes:(pc: A, pd: A)=>pc||pd?`${pc} hit, ${pd} killed (2022)`:'0 hit (2022)',
      adv_sig:(n: A, f: A, d: A)=>`Cross at the light: ${n}, ${f} ft ${d}.`,
      adv_nosig:(n: A, m: A)=>`No light within 800 ft.${n?` Nearest: ${n}, ${m} mi.`:''} Cross at a corner.`,
      adv_x:(n: A, f: A, d: A, g: A)=>`Cross only at ${n}, ${f} ft ${d}${g}.`,gates:' (gates)',flash:' (lights)',
      adv_nox:(n: A, m: A)=>`No rail crossing within 800 ft.${n?` Nearest: ${n}, ${m} mi.`:''}`,
      who:'Who can fix it',
      who_rail:'HISD: bus stop on the home side. City: sidewalk and guard at the crossing.',
      who_toc:(p: A)=>`City. School zone: ${p}’s principal applies by April 15. Guard or crosswalk: 311.`,
      who_local:'City. No school zone on a local street. Guard or crosswalk: 311.',
      shuttle_h:(y: A)=>`Free shuttle from ${y}, through 2027–28`,
      shuttle_b:(from: A, a: A, m: A, x: A)=>`Pickup: ${from}, ${a}, ${m} mi. The walk there ${x}.`,
      xnone:'crosses nothing on the City’s lists',xsome:(list: A)=>`crosses ${list}`,
      shuttle_c:`Stop and times not published. HISD: ${HISD_LINE}.`,
      after_h:'After 2028',after_b:(to: A, m: A)=>`Bus only at 2+ mi. This home: ${m} mi straight-line to ${to}.`,
      after_prek:'Pre-K: no bus or shuttle without an IEP or 504.',
      note_lines:'Straight lines. Real streets cross at least this much.',note_route:'Walking route on mapped streets. Check it on foot.',
      note_lights:'Traffic lights only. Guards and crosswalks are not mapped.',
      dates:'Data dates',
      gethelp:'Get help',askzone:'Ask for a school zone',print:'Print',print_plan:'Print plan',share:'Share',back:'Back',
      map_walk:'Walk',map_line:'Walk (straight line)',map_pick:'To shuttle',map_x:'Crossing',map_light:'Light / rail crossing',map_road:'Dangerous road',map_rail:'Tracks',map_zone:'Old zone',map_bus:'Shuttle pickup',
      help_h:'Two requests',
      bus_h:'Ask HISD for a bus stop',bus_s:'Any time. HISD decides.',zone_h:'Ask the City for a school zone',zone_s:'20 mph signs. Principal applies.',deadline:'Closes April 15',open_bus:'Open',open_zone:'Open',
      give:'Give to',principal:'Principal',principal_of:(s: A)=>`Principal, ${s}`,front:'Front office',call:'Call',school:'School',address:'Address',hisd_line:'HISD family line',council:'Neighborhood council',
      inside:'Included',steps_h:'Steps',
      bus_steps:['Print or share','Principal files it','HISD decides'],
      zone_steps:['Print or share','Principal sends by April 15','Council votes in July'],
      bus_items:['Streets and crash counts','Rail crossing','Suggested bus stop','Neighbors'],
      again:'Ask again each fall until 2028.',dl_h:'Deadline: April 15',dl_s:'Signs go up next school year.',streets:'Streets',streets_none:'No street here can get a school zone. Asks for a guard and crosswalk.',
      preview:'Preview',self_file:'Or file it on HISD’s form',print_req:'Print',
      share_h:'Share',share_school:'Share with the school',your_msg:'Message',
      zones_h:'What changed',big_t:'of the closed-zone area now crosses a dangerous road or tracks.',big_s:(b: A)=>`Before: ${b} in 10.`,shareof:'Area crossing a dangerous road or tracks',lb:'Before',ln:'Now',checkaddr:'Check an address',pct_note:'Share of area, not homes.',
      in10:'in 10',all:'Nearly all',zd_t:'of homes cross a dangerous road or tracks.',zd_b:(b: A)=>`Before: ${b} in 10.`,haz:'Dangerous road or tracks',railx:'Tracks',farther:'farther',over2:'2+ mi',longest:'longest',
      pickup_h:'Walk to the shuttle',pickup_b:(n: A, a: A)=>`${n}, ${a}. Roads crossed:`,
      pick_h:'Tap your home',use:'Use this spot',spot:'Map spot',
      plan_h:'Walk plan',bring:'Bus stop or school zone?',bring_b:(n: A, p: A)=>`Take this to the front office. Ask for ${n}${p?' · '+p:''}.`,
      staff_h:'Staff',staff_only:'English only.',sources_h:'Sources',
      src_cols:['Source','Used for','Date']
    }
;

export type UiDict = typeof en;

const es: UiDict = {
      h_check:'Revise el camino de su hijo a la escuela',addr:'Dirección',addr_ph:'1234 Main St',go:'Revisar',checking:'Revisando…',
      demo:'Usar dirección de ejemplo',pick:'Marcar en el mapa',examples:'Ejemplos',ex_sub:'Casas en las 7 zonas cerradas',
      bad_addr:(ex: A)=>`Escriba número y calle. Ejemplo: ${ex}`,notfound:'No se encontró. Use el ejemplo o marque en el mapa.',
      v_red:'Peligro',v_red_s:'Cruces sin semáforo',v_yellow:'Cuidado',v_yellow_s:'Cruce solo en los semáforos',v_green:'Despejado',v_green_s:'Sin cruces peligrosos',
      your_school:'Escuela',dangers:'Puntos de peligro',none:'Ninguno',contacts:'A quién llamar',call_hisd:'Llamar a HISD',email_city:'Escribir a la Ciudad',school_office:'Oficina de la escuela',
      shuttle_line:(from: A)=>`Autobús gratis desde ${from} hasta 2028`,askbus:'Pedir autobús',details:'Todos los detalles',
      d_nolight:'Sin semáforo',d_nox:'Sin cruce de vías',d_light:(f: A)=>`Semáforo ${f}`,d_gate:(f: A)=>`Barrera ${f}`,d_xing:(f: A)=>`Cruce de vías ${f}`,dir:(d: A)=>DIR_ES_SHORT[d] ?? d,
      rail_name:'Vías de tren',mi_walk:(m: A)=>`${m} mi en línea recta`,
      nz_h:'Fuera de las zonas de primaria de HISD',another:'Otra dirección',
      nav_check:'Revisar',nav_schools:'Escuelas',nav_about:'Acerca',nav_staff:'Personal',
      about_h:'Acerca',about_b:['HISD cerró 7 primarias en 2026.','Los niños caminan más lejos, por calles más peligrosas.','Este sitio muestra cada camino. Solo datos públicos.'],
      about_links:'Más',
      ask:'Preguntar',ask_h:'Pregunte sobre este camino',
      grade_q:'Grado',grade_k:'K–5',grade_pk:'Pre-K',found:'Encontrada',fix:'Corregir',usemine:'Usar mi dirección',mins:(n: A)=>`${n} min`,shuttle_s:'autobús hasta 2028',
      ask_rail:'Pida a HISD una parada',ask_toc:(p: A)=>`Pida a la Ciudad, vía el director de ${p}`,ask_local:'Pida a la Ciudad vía 311',key:'Leyenda',
      copy:'Copiar',copied:'Copiado',close:'Cerrar',opens_mail:'Abre el correo.',opens_msgs:'Abre mensajes.',showmap:'Mapa',walkto:'Camino a',
      shared_h:'Camino compartido.',shared_b:'Revise el suyo',
      coop_win:'Ctrl + desplazar para acercar',coop_mac:'⌘ + desplazar para acercar',coop_touch:'Dos dedos para mover',
      days:(n: A)=>`${n} días`,page1:'1 página',doc_en:'En inglés: lo presenta la escuela.',
      plan_title:'Plan del camino',plan_to:(n: A)=>`Plan del camino a ${n}`,plan_for:'Casa',doc_cross:(n: A)=>`${n} cruce${n===1?'':'s'}`,doc_none:'nada que cruzar',plan_order:'Dónde cruzar',plan_nothing:'Nada de las listas de la Ciudad',plan_anyway:'Camínelo una vez para ver las esquinas.',plan_tracks:'Vías de tren',
      plan_shuttle:(from: A, addr: A, m: A, x: A)=>`<b>Autobús gratis de HISD hasta 2027–28.</b> Recoge: ${from}, ${addr}, ${m} mi. El camino ahí ${x}. Horarios: HISD, ${HISD_LINE}.`,plan_xnone:'no cruza nada de las listas de la Ciudad',plan_xsome:(l: A)=>`cruza ${l}`,
      plan_bring:(school: A, who: A, phone: A)=>`<b>¿Parada o zona escolar?</b> Lleve esta página a ${school}. Pregunte por ${who}${phone?' · '+phone:''}.`,plan_principal:'el director',plan_foot:'Líneas rectas, no calles. Solo semáforos.',plan_foot_route:'Ruta a pie por calles del mapa. Solo semáforos.',plan_dates:(a: A, b: A)=>`Choques de la Ciudad 2022 · vías HISD ${a} · semáforos ${b}`,
      src_use:['Escuelas','Zonas cerradas','Zona de una dirección','Calles peligrosas para peatones','Calles con muchos choques','Vías de tren','Semáforos','Cruces públicos de vías','Reglas de zona escolar','Paradas del autobús'],
      closed:'Escuelas que cerraron',see:'Ver el camino',
      src_link:'Fuentes',
      prek_h:'¿Pre-K?',prek_why:'Otras reglas de autobús.',yes:'Sí',yes_s:'Pre-K 3 o 4',no:'No',no_s:'K–5',
      verdict:(to: A, r: A, k: A)=>{const p=[];if(r)p.push(`${r} calle${r>1?'s':''} peligrosa${r>1?'s':''}`);if(k)p.push(k>1?`${k} vías de tren`:'una vía de tren');return `Camino a ${to}: ${p.length?p.join(' + '):'nada de las listas de la Ciudad'}.`;},
      lastyear:'Año pasado',now:'Ahora',nothing:'nada que cruzar',crossings:(n: A)=>`${n} cruce${n===1?'':'s'}`,
      where:'Dónde cruzar',
      tag_ped:'Peligrosa para peatones',tag_hin:'Muchos choques',tag_rail:'Vías activas',
      crashes:(pc: A, pd: A)=>pc||pd?`${pc} atropellados, ${pd} muertos (2022)`:'0 atropellados (2022)',
      adv_sig:(n: A, f: A, d: A)=>`Cruce en el semáforo: ${n}, ${f} pies al ${DIR_ES[d]}.`,
      adv_nosig:(n: A, m: A)=>`Sin semáforo a 800 pies.${n?` Más cercano: ${n}, ${m} mi.`:''} Cruce en una esquina.`,
      adv_x:(n: A, f: A, d: A, g: A)=>`Cruce solo en ${n}, ${f} pies al ${DIR_ES[d]}${g}.`,gates:' (barreras)',flash:' (luces)',
      adv_nox:(n: A, m: A)=>`Sin cruce de vías a 800 pies.${n?` Más cercano: ${n}, ${m} mi.`:''}`,
      who:'Quién lo arregla',
      who_rail:'HISD: parada del lado de la casa. Ciudad: banqueta y guardia en el cruce.',
      who_toc:(p: A)=>`Ciudad. Zona escolar: el director de ${p} la pide antes del 15 de abril. Guardia o paso peatonal: 311.`,
      who_local:'Ciudad. Sin zona escolar en calle local. Guardia o paso peatonal: 311.',
      shuttle_h:(y: A)=>`Autobús gratis desde ${y}, hasta 2027–28`,
      shuttle_b:(from: A, a: A, m: A, x: A)=>`Recoge: ${from}, ${a}, ${m} mi. El camino ahí ${x}.`,
      xnone:'no cruza nada de las listas de la Ciudad',xsome:(list: A)=>`cruza ${list}`,
      shuttle_c:`Parada y horarios sin publicar. HISD: ${HISD_LINE}.`,
      after_h:'Después de 2028',after_b:(to: A, m: A)=>`Autobús solo a 2+ mi. Esta casa: ${m} mi en línea recta a ${to}.`,
      after_prek:'Pre-K: sin autobús sin IEP o 504.',
      note_lines:'Líneas rectas. Las calles reales cruzan al menos esto.',note_route:'Ruta a pie por calles del mapa. Revísela caminando.',
      note_lights:'Solo semáforos. Guardias y pasos pintados no están en mapas.',
      dates:'Fechas',
      gethelp:'Pedir ayuda',askzone:'Pedir zona escolar',print:'Imprimir',print_plan:'Imprimir plan',share:'Compartir',back:'Atrás',
      map_walk:'Camino',map_line:'Camino (línea recta)',map_pick:'Al autobús',map_x:'Cruce',map_light:'Semáforo / cruce de vías',map_road:'Calle peligrosa',map_rail:'Vías',map_zone:'Zona anterior',map_bus:'Parada del autobús',
      help_h:'Dos solicitudes',
      bus_h:'Pedir parada a HISD',bus_s:'Cuando sea. HISD decide.',zone_h:'Pedir zona escolar a la Ciudad',zone_s:'Letreros de 20 mph. El director la pide.',deadline:'Cierra el 15 de abril',open_bus:'Abrir',open_zone:'Abrir',
      give:'Entregar a',principal:'Director(a)',principal_of:(s: A)=>`Director(a), ${s}`,front:'Oficina',call:'Llamar',school:'Escuela',address:'Dirección',hisd_line:'Línea de familias HISD',council:'Consejo del vecindario',
      inside:'Incluye',steps_h:'Pasos',
      bus_steps:['Imprima o comparta','El director lo presenta','HISD decide'],
      zone_steps:['Imprima o comparta','El director lo envía antes del 15 de abril','El Concejo vota en julio'],
      bus_items:['Calles y choques','Cruce de vías','Parada sugerida','Vecinos'],
      again:'Pídalo cada otoño hasta 2028.',dl_h:'Fecha límite: 15 de abril',dl_s:'Letreros el próximo año escolar.',streets:'Calles',streets_none:'Ninguna calle aquí puede tener zona escolar. Pide guardia y paso peatonal.',
      preview:'Vista previa',self_file:'O preséntelo en el formulario de HISD',print_req:'Imprimir',
      share_h:'Compartir',share_school:'Compartir con la escuela',your_msg:'Mensaje',
      zones_h:'Qué cambió',big_t:'del área de las zonas cerradas ahora cruza una calle peligrosa o vías.',big_s:(b: A)=>`Antes: ${b} de 10.`,shareof:'Área que cruza calle peligrosa o vías',lb:'Antes',ln:'Ahora',checkaddr:'Revisar una dirección',pct_note:'Parte del área, no casas.',
      in10:'de 10',all:'Casi todos',zd_t:'de las casas cruzan una calle peligrosa o vías.',zd_b:(b: A)=>`Antes: ${b} de 10.`,haz:'Calle peligrosa o vías',railx:'Vías',farther:'más lejos',over2:'2+ mi',longest:'más largo',
      pickup_h:'Camino al autobús',pickup_b:(n: A, a: A)=>`${n}, ${a}. Calles que cruza:`,
      pick_h:'Toque su casa',use:'Usar este punto',spot:'Punto del mapa',
      plan_h:'Plan del camino',bring:'¿Parada o zona escolar?',bring_b:(n: A, p: A)=>`Lleve esto a la oficina. Pregunte por ${n}${p?' · '+p:''}.`,
      staff_h:'Personal',staff_only:'Solo en inglés.',sources_h:'Fuentes',
      src_cols:['Fuente','Uso','Fecha']
    };

export const UI: Record<"en" | "es", UiDict> = { en, es };
